import './globals.css'
import { Poppins } from 'next/font/google'
import { ThemeAntdProvider } from '@/context/ThemeAntdProvider'
import ReduxProvider from '@/redux/provider'

const inter = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <ReduxProvider>
        <body className={`${inter.className} `}>
          <ThemeAntdProvider>{children}</ThemeAntdProvider>
        </body>
      </ReduxProvider>
    </html>
  )
}
